### ISSUE TITLE
Investigate error message when activating the plugin

### ISSUE THREAD

**Issue by schoenkaft** [grrr-amsterdam/simply-static-deploy#12]
Consistently shows:

> The plugin generated 270 characters of **unexpected output** during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

**Comment by schoenkaft** [comment]
Seems to be caused by calling the empty activation/deactivation hooks (`register_activation_hook` and `register_deactivation_hook`).

**Comment by harmenjanssen** [comment]
Yeah, I'm still a bit sceptical about having empty functions in our plugin. Why would we? This repo is not the plugin scaffold.

**Comment by schoenkaft** [comment]
Yeah, maybe @HammenWS can take a look and comment? I think we're not going to need them because we're not registering post types and stuff like that. Maybe we can remove them, or fix what's causing the problem.

**Comment by HammenWS** [comment]
We can remove them. But I would like to know what causes that error message....
