### ISSUE TITLE
PHP requirements

### ISSUE THREAD

**Issue by Eagerbob** [grrr-amsterdam/simply-static-deploy#31]
When trying to install using composer I get this error message:
 [InvalidArgumentException]                                                   
  Package grrr-amsterdam/simply-static-deploy at version  has a PHP requireme  
  nt incompatible with your PHP version (5.6.30)  

Not sure what this could mean?

Webserver is nginx running PHP 7.3.2 and SQL 5.7.23

**Comment by harmenjanssen** [comment]
We've seen setups where PHP version on the command line differed from the PHP version used by the web server. Maybe that's the case here? 
It's never a desirable situation obviously, especially not when the gap is this wide! 

Could you confirm your PHP version on the command line where you're trying to install?

```
$ php -v
```

**Comment by Eagerbob** [comment]
Yes, that's it. PHP version of my mac was 5.6.30
Upgraded to 7.2 and it now works.
Site runs in Local by Flywheel on my mac.
Plugin is visible in the dashboard.
Thanks!

**Comment by harmenjanssen** [comment]
@Eagerbob Good to know! 👍
