### ISSUE TITLE
500 Error on multisite WP when activate plugin

### ISSUE THREAD

**Issue by JuliaUsanova** [grrr-amsterdam/simply-static-deploy#33]
PHP Version: 7.3
WordPress Version: 5.4.1

I get 500 error when activating the plugin through network admin. In the hosting logs there is:
```
PHP Fatal error:  Uncaught Error: Class 'Grrr\SimplyStaticDeploy\SimplyStaticDeploy' not found in /nas/content/live/cooplenlprod/wp-content/plugins/simply-static-deploy/simply-static-deploy.php:25
```

Stack trace:
```
#0 /nas/content/live/cooplenlprod/wp-settings.php(319): include_once()
#1 /nas/content/live/cooplenlprod/wp-config.php(162): require_once('/nas/content/li...')
#2 /nas/content/live/cooplenlprod/wp-load.php(37): require_once('/nas/content/li...')
#3 /nas/content/live/cooplenlprod/wp-blog-header.php(13): require_once('/nas/content/li...')
#4 /nas/content/live/cooplenlprod/index.php(17): require('/nas/content/li...')
#5 {main}
  thrown in /nas/content/live/cooplenlprod/wp-content/plugins/simply-static-deploy/simply-static-deploy.php on line 25
```

To ensure autoload.php is present:

<img width="649" alt="Screen Shot 2020-05-20 at 21 09 15" src="https://user-images.githubusercontent.com/2921176/82481592-36247e80-9ade-11ea-88bc-4afd082af759.png">

autoloader.php content:
```
<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInitced33dc59fcf74571589a736783f57db::getLoader();
```

wp-config.php
<img width="350" alt="Screen Shot 2020-05-21 at 13 23 24" src="https://user-images.githubusercontent.com/2921176/82549954-72032680-9b66-11ea-94aa-de6e8ae8e34d.png">

**Comment by JuliaUsanova** [comment]
Also tried to activate it on the main site, still get the 500 error

**Comment by HammenWS** [comment]
@JuliaUsanova What happens when you require the composer autoload before requirin `wp-settings.php`? Like

```
require_once(ABSPATH . 'vendor/autoload.php');
require_once(ABSPATH . 'wp-settings.php');
```

**Comment by elreydetoda** [comment]
> @JuliaUsanova What happens when you require the composer autoload before requirin `wp-settings.php`? Like
> 
> ```
> require_once(ABSPATH . 'vendor/autoload.php');
> require_once(ABSPATH . 'wp-settings.php');
> ```

@HammenWS, this fixed it for me! Thank you! I had thought that was a possibility, but am not very acquainted with php stuff so I didn't know if it would make a difference :upside_down_face:
