### ISSUE TITLE
Expecting "("

### ISSUE THREAD

**Issue by LukeArrigoni** [grrr-amsterdam/simply-static-deploy#51]
Hello! 

I just did a fresh install and I'm getting this error:

`[Fri Aug 05 19:40:28.936902 2022] [proxy_fcgi:error] [pid 1940:tid 139770634098432] [client 73.254.239.105:65010] AH01071: Got error 'PHP message: PHP Parse error:  syntax error, unexpected token "match", expecting "(" in /opt/bitnami/wordpress/vendor/grrr-amsterdam/garp-functional/functions/match.php on line 18', referer: http://mydomain.com/wp-admin/`

If you are open to a paid engagement to fix this, let me know. Thanks for your contribution!

**Comment by harmenjanssen** [comment]
Hi @LukeArrigoni! 
This is due to a PHP8-incompatibility in the package [Garp Functional](https://github.com/grrr-amsterdam/garp-functional). 

I'm going to assign my colleague who maintains this package, so we can update the dependency. 
Thanks for bringing this to our attention!

**Comment by HammenWS** [comment]
Will be fixed with #44

**Comment by HammenWS** [comment]
@LukeArrigoni Should be fixed with v2.2.0
